### ISSUE TITLE
[dev mode] Para alguien que desarrolla en Windows, el comando pre-install falla

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#100]
Eso, está pensado para que ejecute bash, no Powershell, hay que ver qué propone npm para eso.

**Comment by MarcosNicolau** [comment]
Hola, @fdodino! :wave:

Soy Marcos, un alumno de la UTN y estoy cursando pdep! Antes que nada decirte que estuve trabajando con todo las herramientas para vs-code y me esta funcionando todo de maravilla la verdad.

Te comento que hace poquito hice un script para setear todo el ambiente de wollok en vs-code ([ver repo](https://github.com/MarcosNicolau/miniature-sniffle/tree/main/wollok)) y un companero que lo quiso correr estaba teniendo problemas en windows.

Justo hoy me hice un fork para tocar unas cositas del game  y de paso me fije esto de la instalación de windows. El problema pasa porque el preinstall ejecuta downloads-libs que hace uso de wget el cual no está disponible en windows. Yo lo que hice fue reemplazarlo por curl.

En lugar de hacer:
`wget -P $LIB_FOLDER "<URL>"`

Quedaría:
`curl -O --create-dirs --output-dir $LIB_FOLDER "<URL>"`

Si te parece, no tengo problema en mandar el pr! :grinning:

**Comment by fdodino** [comment]
Qué copado @MarcosNicolau ! 

Dale, si podés abrite un PR así lo probamos en otra instalación de Windows.

Si estás laburando directamente en VSCode, te instalaste el último release (el que instalamos el fin de semana pasado)? Me interesa ver tu experiencia ahora que integramos el diagrama dinámico con el REPL en el wollok-lsp-ide. Entiendo que vos te instalaste wollok-ts-cli + wollok-lsp-ide y estás trabajando desde el repo de desarrollo, es así? Lo que viene incluso es el agregado del autocomplete (el último PR es por eso)...

**Comment by MarcosNicolau** [comment]
Sisi, estoy con la última versión y el diagrama quedó genial. De hecho, estamos trabajando en el game con mi equipo desde vs-code y estamos andando perfecto, tenemos varias carpetas nesteadas, clases abstractas, packages e imports por todos lados y va todo joya.

Lo único que nos pareció que podría funcionar mejor son algunas cosas del run para el game. Las dimensiones del canvas, por ejemplo, que actualmente, se defaultean a toda las pantalla, no sé pero capaz convendría configurarlo para que tenga las mismas dimensiones del game.height y game.width, y centrarlo. (btw, esto es uno de las cosas que estoy viendo en el fork para ver qué onda).

Más allá de eso, cómo te mencioné, estamos re cómodos y es todo una masa! 😃

Con respecto al pr, lo abro asap.

**Comment by fdodino** [comment]
Uh qué bueno!!

Respecto a tu experiencia, sería piola si 1. cargás issues, o 2. nos mandes un mail (fernando.dodino@gmail.com, nahuel.palumbo@gmail.com @PalumboN ) como para tener en el radar cosas que se nos puedan escapar. Y por supuesto, cuando termines de aprobar la materia te esperamos con los brazos abiertos, la idea es que el año que viene ésta ya sea la versión oficial de Wollok. 

Dale tranquilo con el PR, miércoles y jueves tengo que dar clase así que no lo voy a poder probar hasta el fin de semana.

**Comment by MarcosNicolau** [comment]
Dale buenísimo, a partir de ahora vamos a estar atentos y cualquier cosa que veamos te la comentamos. Por mi parte, decirte que estoy dispuesto a contribuir.  Ahora voy a estar con el fork experimentando y entendiendo bien como funciona todo.

Ah y ahí recién mande el pr y disculpa la tardanza en contestarte!  :grin:

**Comment by fdodino** [comment]
Lo probé en Git Bash y anduvo al pelo.
