### ISSUE TITLE
En la consola REPL puedo definir una var y luego una const con el mismo nombre

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#110]
Es decir, puedo hacer en la misma sesión REPL:

```wollok
var a = 1
// y después 
const a = 2`
```

lo más bien. Lo ideal sería que me diga que ya está definida la variable `a`.

**Comment by PalumboN** [comment]
Al interpretar la segunda variable (o constante) habría que validar si ya no existe _en el mismo contexto?_. 
Hay que tener cuidado de que no evite definir una variable con el mismo nombre en un contexto más chico (que es posible).

https://github.com/uqbar-project/wollok-ts/blob/61ffa0e0efb2db9f5d65d6cb4fb05b49ff651c29/src/interpreter/runtimeModel.ts#L433-L439
