### ISSUE TITLE
Al arrancar el REPL sin diagrama dinámico no muestra el prompt

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#114]
Esto es porque quedó atado a que se muestre cuando el server del diagrama da el ok, me parece. Habría que hacer la pregunta para saber si mostramos o no el prompt inmediatamente o una vez que arrancó el server del diagrama dinámico.

**Comment by fdodino** [comment]
En realidad era un problema del diagrama dinámico, que no estaba levantando por un probable cambio en el path... algo raro. Cierro el issue.

**Comment by PalumboN** [comment]
Perdón que re-abra el issue, pero tal vez estaría bueno poder levantar el REPL sin estar atado al diagrama

**Comment by fdodino** [comment]
Sí, el fin de semana pensaba eso... me parece bien

**Comment by fdodino** [comment]
Cierro porque quedó implementado con la opción `--skipDiagram`

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/1d497e07-1888-493a-b2d1-55b4b302ed1a)
