### ISSUE TITLE
El CLI debería poderse ejecutar desde cualquier carpeta

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#12]
Sería genial poder escribir "wollok repl" en cualquier consola en cualquier carpeta y que eso abra un repl de wollok.

Hoy para hacer eso es tan sencillo como buildear este proyecto para obtener el ejecutable y:
- Poner la carpeta donde está el ejecutable "wollok" en el PATH del sistema operativo o bien
- Poner el ejecutable "wollok" dentro de una carpeta que ya esté en el PATH (como C:\Windows\System32 en windows, o /usr/bin en linux).

Si bien es algo bastante pavo de hacer (y hoy de hecho ya lo hacen, a veces, para instalar java) (no la mayoría), estaría bueno que este CLI no necesitara eso, y tuviera una forma de "instalarse" y "desinstalarse".

Veo dos caminos posibles:
- Buscar una herramienta como [electron-builder](https://www.electron.build/) que me da instaladores automáticamente para todo sistema operativo, me resuelve el tema de firmarlos y todo (Windows y Mac son especialmente molestos con el tema de la firma) o bien
- Resolverlo todo a pulmón como en [pilas bloques](https://github.com/Program-AR/pilas-bloques/blob/develop/scripts/package.sh), donde usamos `electron-installer-debian` para los deb de Linux, NSIS para Windows (con la herramienta `makensis`) y `hdiutil` para mac, que hacer los .dmg. Pero ya estos tienen problemas reportados en Pilas Bloques, así que yo investigaría de nuevo bastante.

Esta investigación puede ser un buen puntapié inicial por si queremos en algún momento empaquetar algo más que sólo el CLI.

¿@uqbar-project/wollok opiniones?

**Comment by fdodino** [comment]
Muy piola, no lo conocía.

Yo diría que electron-builder es lo que queríamos, al menos para una prueba de concepto es la que intentaría.

**Comment by fdodino** [comment]
Sí, por eso una prueba de concepto rápida nos va a dar algunas respuestas de lo que nos da vs. Lo que pagamos por usarla

**Comment by asanzo** [comment]
@FerRomMu estuvo progresando. Todavía no podemos hacerlo andar bien pero por lo menos está generando los instaladores usando electron-builder.

- [ ] Ahora está tirando un error "unknown option --no-sandbox" , hay que intentar solucionarlo
- [ ] Probar si en Windows y Mac sucede lo mismo (generar desde linux esos instaladores)
- [ ] Intentar ver si podés evitar usar electron-packager, y usar sólo electron-builder.

**Comment by asanzo** [comment]
De las pruebas aprendimos lo siguiente.

- Para tener andando electron-builder, hay que usar yarn, e instalar `electron-builder` y `electron`.
- Por defecto electron-builder compila a la carpeta `dist`, que es la misma que typescript, lo cual es un poco confuso, así que hicimos que el `tsc` compilara a una carpeta que es `tscOut`, porque no encontramos la forma de cambiar el out de electron-builder.
- Además, en el package.json hay que agregar el `main` y una configuración de `electron-builder`, que es `build`, y algunos scripts, este es el resumen:

```json
  "scripts": {
    "build": "rm -rf tscOut && tsc",
    "postinstall": "electron-builder install-app-deps",
    "dist": "electron-builder"
  },
  "main": "./tscOut/index.js",
  "build":{
    "files": [
      "tscOut/**/*"
    ]
  },
```
(Acá se ve cómo cambiamos el out de tsconfig.json a la carpeta tscOut para hacer estas pruebas)

###
- Definitivamente no es necesario el electron-packager.
- Fer se hizo una lista de cosas que probó. Estas son:

### Linux
- El snap instala bien, y pone el cli disponible en el PATH (yay! :clap: :clap: ) y anda el `--help`, pero estalla el `wollok repl` con el problema  "unknown option --no-sandbox". 
- Posible próximo paso: Sospechamos que habría que ver de deshabilitar el sandboxing del Chromium que provee Electron.

### Windows
- Para generarlo desde linux, hay que tener instalado wine y wine32 . Genera el instalador (y desinstalador) muy bien, incluso lo pone en el menú inicio, pero: NO pone el cli en el PATH (BUH :cry: ) y además se frula la consola cuando hacés `wollok repl`
- Posible próximo paso: probar buildear desde Win.

### Mac
- Intentando buildear desde linux, falla con el error "Cannot find module 'dmg-license'", y al intentar hacer el yarn install de ese módulo dice que no podés hacer esto desde linux: `The platform "linux" is incompatible with this module.` 
- Posible próximo paso: probar buildear desde Mac.

------------------------------

### Conclusión

Yo abandonaría las pruebas con electron-builder por ahora. Los instaladores están pesando 70MB y estamos teniendo problemas que tienen que ver con shipear innecesariamente Electron, como esperábamos.

Pondría por ahora este issue en pausa, para liberar la cabeza. Estoy tentado a resolver cada instalación de cada sistema operativo por separado Oooooooo a resolverlo sencillamente con un instructivo de cómo agregar wollok al PATH.

**Comment by PalumboN** [comment]
Yo creo que con que la gente lo agregue al PATH a mano estamos bien. Con eso ya se puede usar como dice el issue.

**Comment by fdodino** [comment]
En el README tenemos ahora un instructivo de cómo hay que agregarlo al PATH para Windows, Mac y Linux. Cierro el ticket porque me parece que tenemos un _good enough approach_.
