### ISSUE TITLE
No me anda el ejecutable en macos

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#127]
Me descargué el ejecutable del [último release](https://github.com/uqbar-project/wollok-ts-cli/releases/tag/v0.2.0) e hice esto:
```bash
➜  concurso2023 chmod 775 wollok-ts-cli-macos-arm64-oficial
➜  concurso2023 xattr -d com.apple.quarantine wollok-ts-cli-macos-arm64-oficial 
➜  concurso2023 ./wollok-ts-cli-macos-arm64-oficial --version                  
[1]    7782 killed     ./wollok-ts-cli-macos-arm64-oficial --version
```

Pero no me funciona, se me muere al toque :(

Si la buildeo desde el repo me funca (sin hacer nada de eso).

Todo esto debería estar documentado en este repo y [en el sitio](https://uqbar-project.github.io/website-wollok-ts/getting_started/installation/).

**Comment by PalumboN** [comment]
El CI está tirando este error para arm64:
```bash
> Warning Failed to make bytecode node18-arm64 for file /snapshot/wollok-ts-cli/build/src/index.js
> Warning Failed to make bytecode node18-arm64 for file /snapshot/wollok-ts-cli/build/src/logger.js
> Warning Failed to make bytecode node18-arm64 for file /snapshot/wollok-ts-cli/build/src/time-measurer.js
```

En Linux funciona 👍

**Comment by fdodino** [comment]
@PalumboN ésto yo lo probé hace 1 semana y me funcionó ok. Cerramos el issue?

**Comment by PalumboN** [comment]
Lo probaste con una ARM?

**Comment by fdodino** [comment]
> Lo probaste con una ARM?

sí, es una M1

<img width="478" alt="image" src="https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/984e9643-0637-4593-b594-9888234d2752">
