### ISSUE TITLE
Error por constante llamada wollok

### ISSUE THREAD

**Issue by julimr** [uqbar-project/wollok-ts-cli#15]
Estamos probando este [proyecto](https://github.com/wollok/IntegradorVirus) y nos tira este error:
`[ERROR]: missingReference at src/test.wtest:--`

Llegamos a este mínimo test, si le cambiamos el nombre a la contante wollok por wollok2 el error desaparece.
```wollok
import computadora.*
import programas.*

describe "TESTEOS DE PROGRAMA"{
	const windows = new SistemaOperativo(memoria = 2, disco = 2)
	const miPc = new Computadora(sistemaOperativo = windows, discoTotal = 150, memoriaTotal = 8)
	
	const wollok= new Programa(memoria = 1, disco = 4)

	test "ejecutar windows"	{
		miPc.ejecutar(windows)
		assert.equals([windows], miPc.programasEnEjecucion())
	}
}
```

**Comment by nscarcella** [comment]
Seh. `wollok` es el nombre del package global de Wollok. Todas las clases globales están incluidas en ese package (por ejemplo, `wollok.lang.Object`) y ocultarlo sería más bien problemático porque haría que no se puedan resolver los nombres de nada global.

Yo diría que la propuesta más simple es no dejar que nada se llame wollok. Tal vez podría agregarse a la lista de palabras reservadas que ya validamos.

**Comment by asanzo** [comment]
En otras palabras, al buildear o validar debería saltar un error. Quizás mejor al buildear.

**Comment by julimr** [comment]
[Test en wollok-language](https://github.com/uqbar-project/wollok-language/pull/142)

**Comment by lspigariol** [comment]
reabro para advertir y preveer ajustes asociados:
- En wollok xtext el ejemplo de archivo wlk que se crea solo al hacer un proyecto nuevo define un `object wollok` 
- La documentación en el sitio incluye ejemplos donde tambien se define `object wollok`

**Comment by nscarcella** [comment]
Capaz habría que crear tickets en esos proyectos. No creo que desde acá
tenga visibilidad

**Comment by fdodino** [comment]
Cierro el ticket pensando en que

- wollok-ts-cli ya tiene un init donde no se crea un objeto wollok
- va a haber un nuevo sitio para febrero/marzo 2024
