### ISSUE TITLE
Mejorar la forma de presentar un fondo para un juego

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#154]
Hoy el `ground` no se actualiza, aun cuando le setees un valor

```wollok
game.ground(...)

game.start()  // se visualiza el ground por defecto
```

**Comment by fdodino** [comment]
No se está tomando en cuenta `ground` directamente. Deberíamos tener:

- boardGround como fondo adaptado en la imagen
- ground como fondo de celda que se repita

**Comment by PalumboN** [comment]
Y si están ambos, fondo de canvas mata fondo de celda (el fondo de la celda viene por defecto, el otro no).
