### ISSUE TITLE
Los domain exception no se están capturando en el movimiento del character

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#156]
Ver ejemplo del [Sokoban](https://github.com/wollok/sokobanGame/blob/master/caja.wlk), sí funciona para el evento del teclado en el [Tamagotchi](https://github.com/wollok/tamagotchiGameComposicion/blob/master/game/pgmMain.wpgm)

![errorSokoban](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/e90a2feb-7caa-4b10-a8da-c6b35182e0c4)

**Comment by PalumboN** [comment]
@fdodino esto no se soluciona con lo que hablamos el otro día?

**Comment by fdodino** [comment]
> @fdodino esto no se soluciona con lo que hablamos el otro día?

Entiendo que no, porque yo le puse como source el personaje. Me parece que debe estar ocurriendo en otro evento.

**Comment by PalumboN** [comment]
En ese juego al final el problema era el `try catch`
https://github.com/wollok/sokobanGame/blob/23a69379dde279b894d74bb22846b284682a3e6e/sokoban.wlk#L8-L15

@fdodino confirmás?

**Comment by fdodino** [comment]
> En ese juego al final el problema era el `try catch` https://github.com/wollok/sokobanGame/blob/23a69379dde279b894d74bb22846b284682a3e6e/sokoban.wlk#L8-L15
> 
> @fdodino confirmás?

no, el problema es que el personaje no dice nada en los dos lugares donde se tira la excepción:

```wlk
	method validarLugarLibre(direccion) {
		const posAlLado = direccion.siguiente(position)
		const lugarLibre = game.getObjectsIn(posAlLado).all(
			{ obj => obj.puedePisarte(self) }
		)
		if (!lugarLibre) {
			throw new DomainException(message = "Algo traba la caja.", source = sokoban)
		}
	}

        method movete(direccion) {
		throw new DomainException(message = "No puedes mover las paredes.")
	}
```

Lo que recibimos es un catch. Lo peor es que si sacás el try/catch la excepción se pierde, ni se informa:

```wlk
		game.whenCollideDo(sokoban, { elemento => sokoban.empuja(elemento) })
```

yo miraría la implementación de todos los métodos que nos permitan definir comportamiento en un juego, sospecho que hay un temilla ahí de no atrapar la excepción antes de que salte (al igual que pasaba en el LSP).

**Comment by PalumboN** [comment]
Mmmm pero yo probé ese día relanzando la excepción y me funcionó (la línea que digo evita que la excepción llegue a game)
No parecía ser un error de game sino de cómo está hecho el juego.

Miremoslo juntos!

**Comment by fdodino** [comment]
> Mmmm pero yo probé ese día relanzando la excepción y me funcionó (la línea que digo evita que la excepción llegue a game) No parecía ser un error de game sino de cómo está hecho el juego.
> 
> Miremoslo juntos!

Dale!

**Comment by PalumboN** [comment]
Ahí pudimos solucionar el issue y abrimos otros 💪
