### ISSUE TITLE
unObjecto.toString() devuelve "ubicacion.unObjeto"

### ISSUE THREAD

**Issue by FerRomMu** [uqbar-project/wollok-ts-cli#16]
Cuando se realiza toString() de un objeto en vez de devolver el nombre del objeto como un string devuelve un string con la ubicacion de este "." y el nombre del objeto.

Por ej:

![Captura de pantalla de 2022-06-03 16-46-21](https://user-images.githubusercontent.com/70177008/171939606-0352db7b-4e81-477a-9946-d8034ffeb57d.png)

Cabe destacar que como bien se ve en el ejemplo y como se especifico en este issue:
https://github.com/uqbar-project/wollok-ts-cli/issues/4

Actualmente el objeto en cuestion para ser referenciado requiere su ubicación por lo que probablemente resolver ese issue resuelva este.

**Comment by asanzo** [comment]
Cierro porque está duplicado.
https://github.com/uqbar-project/wollok-ts/issues/114
