### ISSUE TITLE
Problema de instalación en windows - Failed to remove some directories

### ISSUE THREAD

**Issue by facu777** [uqbar-project/wollok-ts-cli#168]
Estaba instalando wollok-ts-cli en mi compu con windows 11 utlizando npm en su ultima versión y node v20.6.1 con el comando ```npm i -g wollok-ts-cli``` en powershell. Me aparece el siguiente error:

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/49029994/57dd32a8-48ae-4295-8e4d-bd718ff4f5f3)

Con permisos de administrador me aparece lo siguiente:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/49029994/5b671e5b-8ccc-4bc7-bc84-48db50b6e3b3)

**Comment by PalumboN** [comment]
Sí, al parecer la culpable es esta línea:

https://github.com/uqbar-project/wollok-ts-cli/blob/1d9df8144f01e5e438b509c1f67410c83fa98008/package.json#L22

que solo funciona en **Bash**.

Todavía no tenemos soporte para Powershell, pero podemos dejar este issue abierto para hacerlo en un futuro.

Por ahora mi recomendación es que intentes en otra consola, alguna que sea bash, no powershell.
