### ISSUE TITLE
Error "codeShouldBeReachable" cuando corro tests con booleans

### ISSUE THREAD

**Issue by julimr** [uqbar-project/wollok-ts-cli#17]
Probando los test de [wollok-language/sanity/basics/booleans/literals](https://github.com/uqbar-project/wollok-language/blob/master/test/sanity/basics/booleans/literals.wtest)
Tira este error en la consola `[ERROR]: codeShouldBeReachable at literals.wtest:41`

Llegué a este mínimo test, donde tira el mismo error:
```wollok
test "and operator used with literals true and false"{
    assert.notThat(false && true)
}
```
También pasa con estos asserts:
```
//assert.notThat(false and true)
//assert.notThat(false && false)
//assert.notThat(false and false)
//assert.that(true || true)
//assert.that(true or true)
//assert.that(true || false)
```

**Comment by nscarcella** [comment]
Sí, tiene sentido. Por un lado la validación exige que el código sea "alcanzable", es decir, que a todos los nodos se llegue por algún flujo de ejecución. Por otro lado, los operadores booleanos short-circuitean. Esto quiere decir que el segundo parámetro nunca se ejecuta si el primero falla la operación (por ejemplo, `false && ...` ya es false, no importa lo que diga el parametro derecho).

Entonces hay una contradicción, la validación no puede pasar sobre esos tests que, por otro lado, no me queda claro qué testean (en particular no me queda claro porqué dicen tan específicamente que testean literales...). Creo que un test igual de valioso que no tendría ningún conflicto sería reemplazar esos literales por constantes:
```wollok
const t = true
const f = false
```
Qué opinan @fdodino y @asanzo ?

**Comment by fdodino** [comment]
Yo creo que es un caso borde, cuando lo use una persona el código que escriba después de `false &&` no tiene sentido y está bien que tire error. Después podemos desactivar esa validación para este test específico o hacer el workaround que propone @nscarcella .

**Comment by nscarcella** [comment]
> Este error sucede porque se corrió `wollok test` sobre la carpeta de los tests de sanity de language, y los tests de sanity van a tener siempre muchos errores y problemas de validación, porque esa es la idea.

Ojo... Es posible que ahora mismo tengamos validaciones que fallan en los sanity, pero esa definitivamente no es la idea. En los tests de validaciones ciertamente esperamos que hayan validaciones que no pasen y por eso hay una annotation ahí que nos permite esperar que ocurra pero, en principio, no hay ninguna razón para que los tests de sanity no cumplan con las reglas de validación que le damos a los pibes. Más aún, sería muy deseable que pase.

Los tests de sanity describen código Wollok "correcto", con lo cual, si se falla una validación, sería bueno aunque sea que nos paremos un toque a pensar si ese test puede escribirse de otra forma (cosa de no dejar un mal ejemplo en nuestro propio código) o si la validación realmente se porta cómo queremos. Obviamente hay casos border, pero no nos quedemos con que los sanity están fuera de la ley porque no.

**Comment by asanzo** [comment]
@nscarcella 
Perá, pero justo en este caso estoy probando el && . ¿"Bypassear" la validation poniendo un `const t = true` no es meter otra cosa fea en el código (renombrar los booleanos)? Te lo planteo de otra forma: en un futuro yo re querría agregar la validación ultra cheta que se dé cuenta aún de cuando hiciste esa trampa (Creo que incluso typescript la tiene). ¿Y ahí vamos a hacer otra trampa ultra compleja para que no salten las validaciones en los sanity?

Hmmmmm creo que en este caso quiero tener un "apagame el validator de reachability en esta línea por favor" como en otros lenguajes, y tenerlo en Wollok. ¿Tiene sentido lo que digo? entonces lo pongo arriba de las líneas/definiciones que sé que va a saltar ese validador. ¿O quizás haya que usar las mismas annotations que hoy existen y agregarlas al lenguaje?
