### ISSUE TITLE
Instalar con node y correr un test desde CMD tiene problemas

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#172]
El error que tira es que `está deshabilitada la ejecución de scripts`.

Quizá sea un problema de permisos con Windows, probando con Bash funciona (PowerShell no siempre).

Habría que probar de levantar CMD como admin sino.

#### Estaría bueno tenerlo documentado en el sitio.

(Le pasó a Andrea en la presentación de la facu)

**Comment by fdodino** [comment]
@PalumboN no es igual a #174 ?

**Comment by PalumboN** [comment]
Sí, es el mismo problema. Cierro los 2.
