### ISSUE TITLE
Powershell: No puedo correr wollok cli por ejecución de scripts deshabilitada

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#174]
Instalación Windows 11 Pro 23H2
Versión 22631.3737

Desde PowerShell:
- Instalé npm
- Hice el npm install -g wollok-ts-cli
- Intenté correr wollok init
- Reinicié el powershell, no se soluciona.

<img width="646" alt="image" src="https://github.com/user-attachments/assets/d921aa75-c040-4a5f-8176-204ebe93a269">

```bash
wollok : No se puede cargar el archivo C:\Users\Usuario\AppData\Roaming\npm\wollok.ps1 porque la ejecución de scripts
está deshabilitada en este sistema. Para obtener más información, consulta el tema about_Execution_Policies en
https:/go.microsoft.com/fwlink/?LinkID=135170.
En línea: 1 Carácter: 1
+ wollok init
+ ~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok-ts-cli/issues/172

**Comment by PalumboN** [comment]
Creo que @JuanFdS había encontrado que borrando ese archivo `wollok.ps1` el problema se soluciona 🤷

**Comment by fdodino** [comment]
Creo que este issue ya se puede cerrar... @PalumboN ahora que tenemos la sección de Problemas comunes

**Comment by PalumboN** [comment]
🫡
