### ISSUE TITLE
game.clear() cuelga el juego

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#181]
Eso.

**Comment by PalumboN** [comment]
El otro día vimos que el problema es que ahora el loop del render está como un onTick del game: https://github.com/uqbar-project/wollok-ts-cli/blob/f4efde47a6ec5c6103a6012a9a026cf4fb85f6a4/src/commands/run.ts#L109

Entonces al hacer clear se borra ese onTick.

Esto se soluciona con este PR https://github.com/uqbar-project/wollok-ts-cli/pull/163 (que hay que actualizar, quedó un toque viejo). Ese PR saca el loop del lado de CLI, sin pasar por los eventos de WGame.
