### ISSUE TITLE
Añadir el comando "reload" al cli

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#19]
Este comando debe reiniciar absolutamente todo desde 0. Es para resolver el ["TODO:"](https://github.com/uqbar-project/wollok-ts-cli/blob/c9d1619506198369fb0bef670b665670210257c9/src/commands/repl.ts#L107) dejado en el código.

Posible descripción:
```
  :reload | :r  Reloads all currently imported packages returning to an initial state.
```

**Comment by nscarcella** [comment]
Viendo este ticket imagino que es de lo que hablaba en el ticket #20 . Algo para tener en cuenta es que no me parece buena idea llamarle clean a este y reload al otro. En todas las otras tecnologías que usamos en clase el reload tiene un atajo y una semántica equivalente a lo que acá estamos llamando "clean", para mi eso da para quilombo.

Yo mantendría el reload haciendo reload y, si querés un comando más loco que haga reload y además te haga un re-run de algunas lineas, pensaría un nombre mejor para ese.

**Comment by asanzo** [comment]
De acuerdo. Dejo este issue para resolver el reload como decís.

**Comment by FerRomMu** [comment]
> * [ ]  Volver a construir un intérprete con una nueva evaluación con el nuevo environment creado a partir de los nuevos archivos modificados.

Cambios sugeridos en #24 (No estoy seguro de que debiera estar en otro pr pero eso entendí el otro día).
