### ISSUE TITLE
Codear el comando "reload and rerun" del cli

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#20]
Posible descripción:

` :rr | Same as "reload" but additionaly reruns all commands written since last reload`

- En #19 ya hablamos sobre cómo implementar esto.
- [ ] Hay que poder acceder a la lista de cosas escritas. Una posible forma de resolverlo sería ver si no se le puede preguntar la lista de cosas escritas en consola al objeto REPL. Otra posible forma sería guardarse esas cosas a mano.
- [ ] Luego, simplemente hacer un reload, y correr una por una esas cosas.
- [ ] Esto estaría bueno testearlo (que efectivamente haya corrido de nuevo, que funcione un doesnotunderstand anterior, etc.) Pero para eso probablemente sea necesario resolver antes: https://github.com/uqbar-project/wollok-ts-cli/issues/21

**Comment by nscarcella** [comment]
@asanzo poneme un calendar o algo así y lo charlamos.

Yo tendría cuidado con lo de "and reruns all commands from this session". No hay nada que defina lo que es una sesión. Sí hacés un cambio en el código que rompa lo que escribiste en la consola el reload va a quedar roto. Calculo que, como mínimo, necesitás un reload que sólo recargue los archivos y en todo caso ponés otro comando que re-ejecute la "sesión" anterior. De hecho, eso permitiría separarlo en tickets más chicos. Lo dejo a tu criterio.

Igual confieso que a mi me da un poco de vertigo eso de ejecutar lineas que no estoy viendo... En clase yo prefiero escribir esa inicialización en el cuerpo de un método y mandar un sólo mensaje desde la consola, cosa de que no sea incomodo pero tampoco sea demasiado mágico... Pero bueno, cada uno con lo suyo. Sólo no rompamos el reload básico...

**Comment by asanzo** [comment]
@nscarcella De acuerdo con que el reload básico exista como decís. Este feature que pedimos acá es secundario.
Apuntemos al otro y después vemos qué onda este.

**Comment by PalumboN** [comment]
A mí me gusta este feature, en clase tenemos una dinámica que se usa en forma de un "proto TDD" (antes de ver tests).

Si tu programa rompe lo que escribiste antes entonces debería fallar, como pasaba también en Eclipse.

**Comment by fdodino** [comment]
acá va un preview:

![Uploading reloadAndRerun.gif…]()
