### ISSUE TITLE
Agregar tests E2E

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#21]
Como dice @nscarcella , esto es un CLI, tiene sentido tener tests de CLI.

- La idea sería poder probar cosas como "escribo esto, pasa esto"
- Se pueden buscar herramientas. La primera que me saltó es esta, pero por favor googleemos más: https://github.com/node-modules/clet . Veamos si vale la pena hacer lo que hace [esta persona](https://medium.com/@zorrodg/integration-tests-on-node-js-cli-part-2-testing-interaction-user-input-6f345d4b713a) que testea todo a mano o tener algo que facilite.

**Comment by PalumboN** [comment]
Acá agregué unos tests para el REPL, sin ninguna magia rara pero bastante E2E: https://github.com/uqbar-project/wollok-ts-cli/pull/42

Fijate qué tepa @asanzo y comentá o cerrá el issue porfa :)
