### ISSUE TITLE
Agregar stack de ejecución al log de autoimport

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#26]
tenemos que hacer logger.info(lo que le queremos decir a el/la estudiante) y logger.debug(el stack) al imprimir el error de autoimport, según lo charlamos acá: https://github.com/uqbar-project/wollok-ts-cli/pull/24/files/62d8e7952f1d563b50a8ffe8aad9fc0e000f6cb2#r915314135

**Comment by FerRomMu** [comment]
Nunca se cerró el anterior pr por lo que al pushear se actualizó. Propongo seguir la charla ahí #24
