### ISSUE TITLE
Aborting run due to validation errors en wollok-ts

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#3]
No me deja correr un proyecto por errores no vinculados al proyecto mismo sino a wollok-ts:

Por las validations shouldUseOverrideKeyword y shouldCatchUsingExceptionHierarchy 

![Selection_029](https://user-images.githubusercontent.com/5421992/166636782-a5bb3ce2-059e-4ce5-800f-389d97d765f4.png)

Esto es usando node 16 y tampoco anda usando node 14 (sospecho que porque justamente el error está en wollok-ts???)

Ahora bien:

Si hago --skipValidations con node 16:
![Selection_028](https://user-images.githubusercontent.com/5421992/166637082-c14f3264-d66b-4139-a6b1-dab9b6a5183e.png)

Sigue teniendo problemas con wollok-ts:

Si hago --skipValidations con node 14 es distinto:

![image](https://user-images.githubusercontent.com/5421992/166637865-fc369183-d56a-46bc-a360-6b29b2944753.png)

Pero eso es porque `replaceAll` está a partir de [node 15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility). 

Acabo de cambiar el Readme en #2 para que mencione esto.

**Comment by asanzo** [comment]
La fase de chequeo de sintaxis creo que la pasa, porque se enoja si hago algo mal:
![Selection_030](https://user-images.githubusercontent.com/5421992/166640345-e879fc74-fcd2-4232-827b-6797a00923ae.png)

Pero luego cuando la sintaxis está bien estalla hasta con un solo archivo, no sólo con un proyecto como le tiré recién:
![image](https://user-images.githubusercontent.com/5421992/166640282-e407d4ec-00f8-4ea4-8344-01e7bc5710ef.png)

**Comment by nscarcella** [comment]
@asanzo Por los errores que tira veo que estás tratando de correr un game. Eso todavía no lo vas a poder hacer porque esto es sólo un evaluador que no tiene motor gráfico (es lo que pensabamos darles a los pasantes): sólo podés correr programas standard.

Por otro lado, la lista de warings y errores que ves es porque ahora mismo language no pasa sus propias validations (más trabajo para pasantes). Sospecho que con @fdodino seteamos el flag para skipearlas en los tests de TS cuando estaba programando las validaciones para no volvernos locos. Habría que corregir language y volver a activarlas, pero eso no sería un issue para este projecto.

El error de las natives creo que es porque no estás pasandole un path al "proyecto" que querés correr. Tené en cuenta que la idea de esto es meterlo en el path global y poder correrlo en cualqueir directorio. En tu ejemplo lo estás corriendo en la carpeta de wollok-cli (que no es un proyecto wollok) y eso hace que quiera importar los archivos de wollok que hay de pedo en node_modules y se trule. Usá el parámetro -p y pasale un project (o buildeá el ejecutable y ponelo en el path y correlo en esa carpeta directamente).

Por otro lado probar de correr con versiones de node/npm incompatibles no va a funcionar. Las que fijaste en el readme tienen sentido.

**Comment by fdodino** [comment]
Solo vengo a decir que recuerdo que al activar validaciones detecté problemas en wollok-language y en su momento los arreglé. Pero bueno... pueden haberse subido cambios y no estoy seguro de que se haya validado desde wollok-ts.

**Comment by asanzo** [comment]
Gracias, Dodineeee :heart: 

@nscarcella Ya puedo correr _el wollok_ con tests y con un repl :heart: :heart: :heart:  GRACIAS

Peeeero me sigue estallando el run del program con un error de `Could not resolve reference to` en `at Environment.getNodeByFQN`

![image](https://user-images.githubusercontent.com/5421992/167491132-c27c9389-136e-4cb9-aea4-6aeffc158ce7.png)

El programa está en `src/programa.wpgm` y el contenido es:

```wollok
program holamundo {
    console.println("si estás viendo esto corre el programa")
}
```

Probé haciendo:
```
./wollok run holamundo
./wollok run src/programa.wpgm
./wollok run programa.wpgm
./wollok run programa
./wollok run .
```

Pero  ninguna de esas funciona, todas tiran el mismo error (`./wollok` es el `wollok-x64-linux-blah` que genera el npm run build)

**Comment by asanzo** [comment]
Con el Rasta pudimos hacerlo andar, lo que era necesario era hacer:

```bash
./wollok run src.programa.holamundo
```

Cargué un issue que tiene que ver con esto: Related https://github.com/uqbar-project/wollok-ts-cli/issues/4
