### ISSUE TITLE
No deberían poderse instanciar WKOs

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#36]
(quizás este issue vaya en wollok-ts)
Con el código de hoy, estoy pudiendo hacer en el REPL `new pepita()`, siendo pepita un wko:

![imagen](https://user-images.githubusercontent.com/5421992/180668447-3ff85111-19c4-4d6f-b874-867b9c19fcc4.png)

Aunque al correr las validaciones da error, el mismo que el issue #35 

```wollok
object pepita{ var property energia = 100 }

object instanciadorDePepitas {
	method instanciar() = new pepita()
}
```
Da el error: `TypeError: _a.isAbstract is not a function`

![imagen](https://user-images.githubusercontent.com/5421992/180668552-bae7e99f-7f80-45c9-8c74-6f1c5667588b.png)

Sería genial que no se pudieran instanciar cosas que no sean clases, y que eso se resuelva antes de validar, ¿quizás en el linkeo?

**Comment by fdodino** [comment]
Confirmo que está solucionado, testeado hoy:

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/7a5dc2eb-aff0-49ff-8f69-4507cb6dfad5)

`pepita` es un object definido en un archivo example.
