### ISSUE TITLE
Mostrar los strings entre comillas

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#38]
Ahora tanto si se imprime un objeto como un string se muestran igual:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/4098184/195661751-730e2b26-4853-4b51-8caf-f196a08d4a0e.png">

Estaría bueno que los String se muestren con las comillas como en el IDE

**Comment by asanzo** [comment]
Relacionado con https://github.com/uqbar-project/wollok-language/issues/140

Lo que pasa es que [acá](https://github.com/uqbar-project/wollok-ts-cli/blob/47b6bed1ea9a8d1b4fc3ed25e2899aa3f9981059/src/commands/repl.ts#L158) estamos mandando el mensaje `toString` cuando sospecho que lo mejor es `printString()`

(Ver por ejemplo [acá con los Strings](https://github.com/uqbar-project/wollok-language/blob/7c804f4b7b47db140c82e50dbafcd9b18232a8f2/src/wollok/lang.wlk#L2359) o [acá con las collection](https://github.com/uqbar-project/wollok-language/blob/7c804f4b7b47db140c82e50dbafcd9b18232a8f2/src/wollok/lang.wlk#L778-L780) )

Hoy @dlopezalvas me dijo que quería meter un PR en Wollok.....

**Comment by PalumboN** [comment]
Como el `toString` tiene problema con los strings pero el `printString` no muestra los elemento de las colecciones, lo dejé como estaba y agregué un if para el caso de los strings.

@asanzo vos ya estuviste laburando en https://github.com/uqbar-project/wollok-language/issues/140, qué crees que es lo mejor?
