### ISSUE TITLE
Scope al correr proyecto

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#4]
El directorio o archivo que se corre debería tener el contexto actual, no tener que ir a buscarlo

En este ejemplo:
![image](https://user-images.githubusercontent.com/5421992/171261450-93e3f29a-c337-45e4-a453-c3a3e6f290f9.png)

Si yo dije que quiero un REPL en src/arch1.wlk no debería tener que hacer import src.arch1.* para llegar a pepita, debería estar directamente disponible

**Comment by nscarcella** [comment]
@asanzo Podríamos pasarnos todo el día discutiendo quién se olvidó de agregar el import que recibimos por parámetro... Pero si checkouteas el head ya anda.

Sin embargo... No hace exactamente lo que describís arriba. Ese ejemplo que ponés tiene que dejar en scope `pepita` y `Golondrina` (además de los paths globales `src.aves.pepita` y `src.aves.Golondrina`), pero `aves.pepita` y `aves.Golondrina` **no deberían estar en scope** salvo que corrás el REPL en la carpeta `src` (o, bueno... con `-p src`).

**Comment by nscarcella** [comment]
Me explayo un poco más por las dudas no haya sido claro:

Si estás corriendo el repl en `./` Cuando vos escribís `repl ./src/aves.wlk` es equivalente a decir `import src.aves.*`. Eso pone el contenido de `src.aves` en scope, pero no el package mismo. Esto tiene que ser así porque, sino, si un packages tiene adentro otra entidad que se llama igual estarías teniendo un conflicto. Entonces lo esperable sería que esté el contenido del package importado, y los nombres globales (qué están siempre aunque no importes nada).

Ahora, si en lugar de correr el REPL en `./` lo corrés en `./src` ahí el path global ya no es `src.aves` sino sólo `aves`, con lo cual ahí sí tendrías `aves` en scope, pero no por el import, sino porque sería un path raiz.

Esto muy difícil de explicar sin dibujitos, pero espero que se entienda. En todo caso a nadie le importa `aves` lo que vos querías que pase es que esté el contenido, y ahora ya debería estar.

**Comment by asanzo** [comment]
GRACIAS LINDO!!!

Fixed in 98bd7d7d99dd5f8a99a48d3723bb842cbd0bb0af
