### ISSUE TITLE
Wollok Game + REPL + Diagrama dinámico = el sueño del pibe

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#43]
Estaría bueno poder abrir Wollok Game desde el REPL también, así se puede usar junto al diagrama dinámico 🤩 

Para eso estaría bueno que el juego se levante al hacer `game.start()`.
Habría que configurar el `drawer` y "sobreescribir" la primitiva para que levante la ventana al buildear cualquier proyecto.

Con eso se podría evaluar el mensaje en el REPL y con eso levantar el juego ;)

**Comment by PalumboN** [comment]
No sé si convence lo que puse en la descripción de este issue, ahora que lo vuelvo a leer meses después. Igual banco al Rasta del pasado de que las cosas del juego se configuren en el `game.start()` y no al correr cualquier programa.

Creo que ahora si querés correr un programa solo (sin game) te abre el juego igual.

Algo que estaría bueno, también relacionado con esto, es **poder abrir el diagrama dinámico con un juego corriendo**. Para que se actualice a medida que el juego se desarrolla. Ivo dice que hay que probar los `onTick` con el diagrama dinámico, no confía en su sync.

**Comment by fdodino** [comment]
Subo la evidencia de las pruebas que hice localmente:

![gameYDynamicDiagram](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/1537e7f4-cbed-4d6c-b2b9-3773bd7f5f29)

**Comment by fdodino** [comment]
Cerramos el ticket, migrado a master
