### ISSUE TITLE
Problema con los paths

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#45]
Dice que hay un problema al buscar las imágenes.

Eso pasa porque [se espera que el proyecto tenga cierta estructura](https://github.com/uqbar-project/wollok-ts-cli/blob/master/src/commands/run.ts#L145) y si no pasa explota todo.

Además, el parámetro `-p` solamente funciona al nivel del package del program... básicamente falla al buscar la entidad si:
- El archivo con el program se encuentra en una subcarpeta del proyecto
- El archivo con el program se llama igual que otra cosa (por más que sí funcionan los tests por ejemplo)

Error:
```
The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:371:5)
at validateString (node:internal/validators:120:11)
at Object.join (node:path:1172:7)
at getImages (/Users/palumbon/git/wollok-ts-cli/dist/mac-arm64/wollok-ts-cli.app/Contents/Resources/app/build/commands/run.js:137:38)
at Namespace.<anonymous> (/Users/palumbon/git/wollok-ts-cli/dist/mac-arm64/wollok-ts-cli.app/Contents/Resources/app/build/commands/run.js:89:31)
at Namespace.emit (node:events:526:28)
at Namespace.emitReserved (/Users/palumbon/git/wollok-ts-cli/dist/mac-arm64/wollok-ts-cli.app/Contents/Resources/app/node_modules/socket.io/dist/typed-events.js:56:22)
at /Users/palumbon/git/wollok-ts-cli/dist/mac-arm64/wollok-ts-cli.app/Contents/Resources/app/node_modules/socket.io/dist/namespace.js:141:26
at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by PalumboN** [comment]
El problema podría estar acá:
https://github.com/uqbar-project/wollok-ts-cli/blob/64b9225a66c6983ac2b091d8a142f0b330d1c714/src/utils.ts#L21-L23

Que se toma como path el absoluto en vez de uno relativo, entonces crea packages desde la base.

**Comment by PalumboN** [comment]
Related to https://github.com/uqbar-project/wollok-ts-cli/issues/53

**Comment by fdodino** [comment]
@PalumboN , hice la prueba con los assets apuntando a un path y para mí está resuelto lo que se puede resolver en wollok-ts-cli. Lo de la colisión de nombres para mí tenemos que arreglarlo en wollok-ts (ya hay un ticket y una larga conversación).

Te dejo un proyecto donde metí assets en distintos subdirectorios, con la opción `-a` dejé también varios tests para asegurarnos de que funcione.

Lo ejecuté

```bash
wollok-ts-cli run mainGame.PepitaGame  -g
```

con el branch `run-command-enhancements` y anduvo ok:

![game-assets](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/249ac4ba-5402-44a5-9156-5f315b7aa920)

[asset-example.tar.gz](https://github.com/uqbar-project/wollok-ts-cli/files/13466750/asset-example.tar.gz)

**Comment by fdodino** [comment]
lo cerramos después de haberlo probado ayer con @PalumboN
