### ISSUE TITLE
Mantener la posición de los objetos en el diagrama dinámico

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#48]
https://user-images.githubusercontent.com/4098184/226188272-9883b576-7583-48a6-b5bc-ee80eb1bf354.mov

**Comment by fdodino** [comment]
@PalumboN , ahora tenemos un pin:

![dynamicDiagramKeepPositions](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/ce86198a-2044-4f5e-9ac1-7bca3eebe01e)

te sirve?

**Comment by fdodino** [comment]
o sea, con el Pin no movemos los objetos que ya están, y los nuevos se acomodan medio al tun tun. Por defecto está desactivado para que se vaya acomodando conforme se crean nuevos nodos.

**Comment by PalumboN** [comment]
Y con el pin activado, todos los objetos se crean en el mismo lugar? Porque @ivojawer había hecho un hack para que aparezcan aleatoriamente pero no todos en el mismo lugar.

**Comment by fdodino** [comment]
no aparecen en el mismo lugar todos, pero al aparecer aleatoriamente medio que se cruzan

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/9767d116-e79a-4fe2-aaa7-793aa164c5d0)

Yo no les defino posición... 

Ahí estuve viendo que [no hay nada custom](https://stackoverflow.com/questions/39423816/prevent-node-overlap-on-add-new-node), pero que [cose](https://js.cytoscape.org/#layouts/cose) trae algunas configuraciones que permiten que agregue elementos y en algunos casos no se produzca colisiones:

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/1f285add-cd95-427c-adc5-974885bfe1c8)

Ahora creo un PR con esas dos configuraciones.
