### ISSUE TITLE
Después de instalar el vsix no me aparece Wollok LSP IDE en la búsqueda de extensiones de VSC

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#49]
Seguí [los pasos de instalación]() del IDE y se instaló correctamente, aunque cuando busqué `wollok` no me aparecía la extensión:

![image](https://user-images.githubusercontent.com/4549002/229096890-ae5e6449-fecc-4454-a118-7a105089cc38.png)

Sí cuando busqué `@sort:updateDate`

![image](https://user-images.githubusercontent.com/4549002/229097191-dd5465c0-0b33-4234-900f-826dfbd79ce7.png)

No es super importante pero por ahí falta alguna descripción en el archivo que genera las versiones y para la próxima se puede investigar.

Abrazo!!
La radio está buenísima!

**Comment by PalumboN** [comment]
@fdodino vamos a estar investigando esto, pero lo creo que pasa es que la extensión no está en el Marketplace de VSCode.

Uqbar ya tiene una cuenta, que es donde está la extensión del highlight. Sabés quién tiene acceso a eso? Para agregar el LSP

**Comment by fdodino** [comment]
Hola @PalumboN , no pude encontrar ningún mail, en su momento lo deployamos con @nscarcella , espero que él tenga la data.
Gracias!!

**Comment by fdodino** [comment]
Era eso @PalumboN , ahora que se publicó en el marketplace lo encontré perfectamente. Cierro el ticket.
