### ISSUE TITLE
Errores en nvm en Windows

### ISSUE THREAD

**Issue by julimr** [uqbar-project/wollok-ts-cli#5]
1. Invalid version en nvm, porque no reconoce el formato lts/gallium en el archivo .nvmrc
2. Aún indicando la versión nvm no funciona: `exit status 1: Acceso denegado.`

![image](https://user-images.githubusercontent.com/78621116/171492274-5c3a3b03-1d70-45ff-8f4c-03469d12e94c.png)

**Comment by asanzo** [comment]
Sobre el error 1., [Acá](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported) Aclaran que nvm para windows **es completamente distinto en todo aspecto** con el nvm para linux y mac, y que jamás soportarán .nvmrc por simple bronca. 

Sobre el error 2., [Acá](https://stackoverflow.com/questions/50563188/access-denied-issue-with-nvm-in-windows-10) lo que dice es que para hacer nvm install y nvm use hay que abrir el powershell o el git bash con permisos de administrador. @julimr probás porfa?

Habría que:
- [ ] Agregar al README , en la parte de hacer `nvm use`, que en Windows habría que mirar el contenido de `.nvmrc` y hacer `nvm use BLAH` donde blah es el contenido de ese archivo
- [ ] Agregar también al README, en ese mismo lugar, que al hacer `nvm use` hay que hacerlo en una consola con privilegios de administrador.

**Comment by julimr** [comment]
Probé lo siguiente y funcionó.
Primero ejecute el `nvm-setup.exe` como administrador y después desde la consola de Git Bash (como administrador) lo siguiente:
![3](https://user-images.githubusercontent.com/78621116/171627786-ee20ed5f-35ad-4352-92bf-106b7a2aee7f.png)
