### ISSUE TITLE
Activar asar

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#50]
Cuando buildeamos dice 

```
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
`
```

https://github.com/uqbar-project/wollok-ts-cli/blob/fdc74a8833023f28ad7abb6070e0747336b602c7/electron-builder.yml#L5

**Comment by ivojawer** [comment]
deprecado ya que sacamos electron
