### ISSUE TITLE
Poder crear un nuevo proyecto desde un template

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#57]
Estaría bueno poder crear un proyecto nuevo, con una estructura prederterminada.

Ejemplos:
- `Proyecto nuevo`: Para ser usado regularmente. Crea un archivo `.wlk` con la definición de un objeto.
- `Tour`: Para ver la sintaxis del lenguaje. Crea archivos `.wlk` `.wtest` `.wpgm` con distintas definiciones.
- `Game`: Crea un template del juego, con los archivos y directorios esperados para ejecutar un juego

También estaría bueno agregar un archivo con metadata del proyecto:
- En un momento se charló de tener un `package.json` (fuimos por esa idea en https://github.com/uqbar-project/wollok-ts-cli/pull/85), pero podría ser cualquier nombre.
- Que tenga
  - nombre del proyecto
  - Versión
  - Versión de Wollok donde se creó / está funcionando
  - assets?
  - main?

**Comment by jschuhmann47** [comment]
Estaría bueno tener algo como tienen Haskell y/o Rust que en la terminal les pasas el comando `init <nombre del proyecto>`(o new) y te crea la plantilla (adjunto foto de `stack`)

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/76596375/0862d258-5196-4a68-bffa-6d9c8d49a64a)
