### ISSUE TITLE
Si abro dos veces el repl, la segunda no puede abrir el diagrama dinámico porque el puerto ya está usado

### ISSUE THREAD

**Issue by JuanFdS** [uqbar-project/wollok-ts-cli#58]
Wollok cli intenta abrir ambas veces en el puerto 3000 y la segunda falla con:

> ✗ File c:/Users/juanm/OneDrive/Documentos/Developmeectos/facu/pdep/Wollok/prueba_file.wlk doesn't exist or is outside of project!
✓ Object diagram available at: http://localhost:3000
wollok> node:events:505
      throw er; // Unhandled 'error' event
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}

Como reproducir:
- correr el repl de wollok cli en una terminal
- una vez abrió, correr el repl de wollok cli en otra

**Comment by PalumboN** [comment]
Y cuál sería el comportamiento esperado?

- Podríamos hacer el checkeo y si no intentar con otro (`3001`?).
- Tirar un error bonito diciendo que el puerto está usado, y que se fije si ya no tiene un Wollok corriendo (me imagino a un estudiante recién iniciado que se puede confundir teniendo muchas sesiones abiertas).

Un poco de cada?

**Comment by fdodino** [comment]
@PalumboN @JuanFdS en [este PR](https://github.com/uqbar-project/wollok-lsp-ide/pull/99) hice que cuando ejecutás el REPL mate todas las sesiones abiertas hasta el momento (igual que pasaba en Xtext) para que no queden puertos abiertos (me parece que para una persona que arranca hacer eso le puede traer problemas de performance y la sensación de que "hay que apagar la compu porque Wollok consume mucha memoria"). Cierro el ticket a menos de que quieras hacer otra cosa.

**Comment by PalumboN** [comment]
Holis! Ese PR sirve para el VSCode, pero qué pasa si uso la CLI por consola?

**Comment by fdodino** [comment]
Buen punto. Resbro....

**Comment by fdodino** [comment]
@PalumboN , qué te parece "un poco de ambas":

- por defecto, que muestre un error amable en lugar del ADDRINUSE
- pero que vos lo puedas forzar (con un `--new`) para que efectivamente te abra otro puerto libre

**Comment by fdodino** [comment]
En realidad, el comportamiento sería
- por defecto, mostrar un error amable, onda 
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/af118ea6-c2df-40cc-b712-a61c5dfeef7c)

- pero más que `--new` debería decir que elijas el puerto disponible vos, con la opción `--port`

**Comment by PalumboN** [comment]
Me parece bien lo del checkeo y la opción del `port` 👍 

Hago estas preguntas / comentarios:
1. Si el puerto está ocupado, **te dejo usar la consola** igual o la mato?
2. En la imagen que pasaste, aún si el puerto está ocupado dice que ✅ el diagrama está disponible :P
3. En el error / warning yo pondría 
`"⚠️ No se pudo levantar el diagrama dinámico porque el puerto 3000 está ocupado. 
Asegurate de no tener otro REPL abierto en otra consola. 
Si querés levantar el diagrama en otro puerto, utilizá la opción..."`

**Comment by fdodino** [comment]
> Si el puerto está ocupado, te dejo usar la consola igual o la mato?
Yo diría de matarlo, porque dejar dos consolas va a ser para que se arme lío o reporten errores que no son tales.

> En la imagen que pasaste, aún si el puerto está ocupado dice que ✅ el diagrama está disponible :P
Sí, eso me molesta, pero todavía no pude ver cómo hacer para detectar de que hubo un error (en realidad supongo que deberíamos ver qué eventos hay para mostrar ese mensaje una vez que efectivamente se conectó).

En paralelo, hay un mensaje que me resulta molesto y es que como usamos socket, cada dos por tres se desconecta y se conecta y eso ensucia la consola. Yo lo que haría es que cuando se desconecte por más de 3 segundos ahí se muestre el mensaje, con lo cual tiraría un setTimeout...

> En el error / warning yo pondría
> "⚠️ No se pudo levantar el diagrama dinámico porque el puerto 3000 está ocupado.  Asegurate de no tener otro REPL abierto en otra consola.  Si querés levantar el diagrama en otro puerto, utilizá la opción..."
Dale!

**Comment by PalumboN** [comment]
Yo no loguearía nada cuando se conectan al diagrama... Como muuuucho lo dejaría para un modo DEBUG

**Comment by fdodino** [comment]
Uhhh... datos de cosas que me pasaron:

1. no logro que el mensajito "Dynamic diagram available..." se muestre solo cuando te conectás, o lo hace una sola vez (incluso cuando te conectás a otros puertos) o lo hace siempre (aun cuando tira error). Voy a seguir investigando.
2. Es gracioso que no me funciona en el navegador el diagrama dinámico para otro puerto distinto del 3000, porque...

```js
        import { io } from "./lib/socket.io.esm.min.js";

        const socket = io("http://localhost:3000");
        socket.on("connect", function () {
```

está hardcodeado el 3000 al server...

Voy a seguir investigando

**Comment by fdodino** [comment]
Listo el pollo, arreglé las dos cositas.
