### ISSUE TITLE
Al correr Start a new REPL Session desde vscode en Windows, no encuentra el archivo actual

### ISSUE THREAD

**Issue by JuanFdS** [uqbar-project/wollok-ts-cli#60]
La ruta del archivo debería ser `c:\Users\juanm\OneDrive\Documentos\Development\proyectos\facu\pdep\Wollok\prueba_file.wlk`, según el mensaje de error no encuentra el archivo en la ruta `c:UsersjuanmOneDriveDocumentosDevelopmentproyectosfacupdepWollokprueba_file.wlk`

> Executing task: C:/Users/juanm/Downloads/wollok-ts-cli-win.exe repl c:\Users\juanm\OneDrive\Documentos\Development\proyectos\facu\pdep\Wollok\prueba_file.wlk -p c:\Users\juanm\OneDrive\Documentos\Development\Initializing Wollok REPL for file c:UsersjuanmOneDriveDocumentosDevelopmentproyectosfacupdepWollokprueba_file.wlk on c:UsersjuanmOneDriveDocumentosDevelopmentproyectosfacupdepWollok
✓ No problems found building the environment!
✗ File c:UsersjuanmOneDriveDocumentosDevelopmentproyectosfacupdepWollokprueba_file.wlk doesn't exist or is outside of project!
✓ Object diagram available at: http://localhost:3000

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/11432672/95fd37b0-ddb1-4813-bb1b-ce9f63e5c4e8)

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/11432672/1e336420-8585-4513-9843-9a7b445b064f)

**Comment by ivojawer** [comment]
Se fixeo en LSP:

https://github.com/uqbar-project/wollok-lsp-ide/pull/75
