### ISSUE TITLE
No mostrar el stack de la VM

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#65]
Puede ser configurable, pero pienso que el default debería ser que no se muestre. Solamente debería aparece si está en modo `DEBUG` o algo así.

Así se ve ahora en el LSP cuando falla un test.

<img width="1076" alt="image" src="https://github.com/uqbar-project/wollok-ts-cli/assets/4098184/32d22175-5d57-4f21-b694-4d98326d5c73">

**Comment by fdodino** [comment]
Sale una migración con fritas!!
