### ISSUE TITLE
Pkg no funciona en Windows

### ISSUE THREAD

**Issue by julimr** [uqbar-project/wollok-ts-cli#7]
```
$ ./node_modules/.bin/pkg .
> pkg@5.6.0
> Targets not specified. Assuming:
  node16-linux-x86, node16-macos-x86, node16-win-x86
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.3","name":"node-v16.14.2-linux-x86"}
> Building base binary from source:
  built-v16.14.2-linux-x86
> Error! Not able to build for 'linux' here, only for 'win'
```

**Comment by asanzo** [comment]
[Acá](https://chowdera.com/2022/04/202204131152340825.html) encontré una posible solución. Básicamente lo que dice es:
- En windows, sólo se puede empaquetar para windows
- En linux se puede empaquetar para cualquier SSOO.

De hecho en el [readme de la tool pkg](https://www.npmjs.com/package/pkg) dice que el único que puede buildear bien para las tres plataformas es linux:
> To be able to generate executables for all supported architectures and platforms, run pkg on a Linux host with binfmt (QEMU emulation) configured and ldid installed.

Lo que yo haría es:
- [ ] Agregar al package.json un script `build:win` que buildee sólo para windows, haciendo un `rm -rf dist && tsc && pkg -t win .` (quizás se puede evitar repetir código con el script de build, por ahí no vale la pena, es pava la repetición).
- [ ] Agregar al README, en el lugar donde dice hacer `npm run build`,  la aclaración de que si estás en Windows, deberías hacer `npm run build:win` para sólo buildear ejecutables de windows porque en windows no se puede buildear para linux porque pkg lo dice.

**Comment by julimr** [comment]
Cambie el package.json agregando `"build:win": "rm -rf dist && tsc && pkg -t win ."`
En la consola ejecuté `npm run build:win`
![image](https://user-images.githubusercontent.com/78621116/171632903-16e5a04d-e7f9-46f0-8e8d-9154472f5071.png)
La carpeta `/dist` quedó así:
![image](https://user-images.githubusercontent.com/78621116/171633272-e6fc8e8a-4fd5-43b4-9aed-aed2deb266c5.png)
