### ISSUE TITLE
Mejorar el diseño (gráfico) del diagrama

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-ts-cli#71]
- Darle una iterada a los colores / formas de los objetos (revisar XText, Dodino hizo un laburo arduo y fantástico encontrando colores, lo que incluía también diferenciaciones para distintos tipos de daltonismo).
- Distintos themes (var https://colorhunt.co/)
Control del tamaño de la font / UI en general
- En la imagen de acá, las palabras true y false no se leen bien
- Los objetos de las colecciones los haría más chicos que el resto (?
Rectángulos para los strings, así entran cómodos. Alf: Me gusta más la forma redonda para todos los objetos, se puede quizás jugar con el tamaño o el borde para diferenciar. Es cómodo para explicar dinámico vs estático que el diagrama dinámico tenga cosas redondas (u ovaladas) versus lo cuadrado/rectangular del diag de clases. Bah, además de cómodo me gusta la metáfora que instancia es redondo y clase es cuadrado.
- Un color particular para los objetos del proyecto (no lang). Alf: En ese sentido, que los objetos "primitivos" o los que vienen dados tengan una forma parecida a un objeto propio me parece una buena decisión didáctica: al fin y al cabo todos son objetos y entienden mensajes. - Si los objetos que le alumne no puede tunearse quiere que sean distintos, podemos jugar con el tamaño (como el ejemplo de achicar el objeto de la colección) y/o el grosor del borde.

**Comment by fdodino** [comment]
Bueno, meto acá la lista que me armé para trabajar en el segundo PR:

- NO está funcionando bien lo del duplicado
- [ ] List/Set en lugar de a List/a Set
- [ ] En Xtext creo que además todas las colecciones (List y Set) se mostraban en línea punteada (qué piensan? Parece que hay consenso en volverlo a poner nomás).
- [ ] hacer tests
- [ ] Ver qué funcionalidad tiene el diagrama en Xtext que falte migrar
- [ ] Que se pueda configurar los colores o al menos themes
- [X] Meterle un canvas interno al VSC, que no tengas que levantar el server o que se pueda configurar (ésto se resolvió en wollok-lsp-ide)
- [ ] Una constante del REPL no figura con el candadito
- [ ] Aparecen los scrollbars al pedo, fijarse content-box
- [ ] Opciones del browser: dark mode, mejorar el botón Organizar
- [ ] Que se pueda configurar si querés abrir un diagrama dinámico cuando levantás el REPL (lsp-ide)
- [ ] Que se pueda configurar si querés abrir un navegador interno o externo (lsp-ide)
- [ ] https://github.com/uqbar-project/wollok-ts-cli/issues/78

HTML
- ponerle 100vh y 100vw al div de cytoscape, el div que engloba las opciones puede tener un relative al padre que sea absolute...
- modo oscuro/claro
- organize
- recalcular automáticamente las posiciones o conservarlas
