### ISSUE TITLE
Multiples referencias desde una lista al mismo objeto

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-ts-cli#78]
Por ejemplo

```wlk
object pepita {
  var amiguxs = [ramon, ramon]

}


object ramon { 
    var valor = 10
}
```

Esto tiene dos problemas

- [ ] Desde la lista a `ramon` se va a ver una unica flecha con nombre "undefined, undefined"
   - Esto se soluciona con #77 pero aun asi pondria if por si las referencias vienen sin nombre.
- [ ] Desde `ramon` a `10` hay dos flechas una con nombre "valor" y otra "valor, valor"

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/18614957/7b4a8137-ddd4-4265-afc0-28a7f7ef11d6)

**Comment by PalumboN** [comment]
Habría que checkear si esto se arregló con https://github.com/uqbar-project/wollok-ts-cli/pull/82

**Comment by ivojawer** [comment]
<img width="849" alt="image" src="https://github.com/uqbar-project/wollok-ts-cli/assets/18614957/7c2deb3c-5afd-4b07-9167-353f98635827">
efectivamente mejoro, pero le falta lo de las dos flechas con "valor"

**Comment by fdodino** [comment]
La verdad es que me costó un montón encontrar dónde estaba, pensé en 3 lugares distintos pero al final el tema estaba acá:

```ts
function getCollections(obj: RuntimeObject, interpreter: Interpreter, alreadyVisited: string[]) {
  const { id } = obj
  return (obj.innerCollection || [])
    .flatMap((item, i) => {
      const result = [
        {
          data: {
            id: `${id}_${item.id}`,
            source: id,
            target: item.id,
            label: isList(obj.module.name) ? i.toString() : '',
          },
        },
        ...elementFromObject(item, interpreter, [...alreadyVisited, id]),
      ]
```

Estábamos agregando el id de la colección, pero faltaba el item, a medida que vamos recorriendo (cada uno de los valores guardados en la colección).

```ts
      // el toque
      alreadyVisited.push(item.id)
      return result
    }
    )
```

**Comment by fdodino** [comment]
Con eso hice la prueba:

```wollok
object pepita {
  var property amiguxs = [ramon, ramon]
  method agregarAmiwi(nuevoAmiwi) { amiguxs.add(nuevoAmiwi)}
}

object ramon { 
    var valor = 10
}
```

Y en el REPL hice

```ẁollok
wollok:example> pepita.agregarAmiwi(2)
✓ 
wollok:example> pepita.agregarAmiwi(10)
✓ 
wollok:example> pepita.agregarAmiwi(ramon)
```

Para obtener

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/b7e33aa9-a341-4e6f-bfb4-b445a94dc9c1)
