### ISSUE TITLE
Revisar los permisos de los ejecutables

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#79]
Los deploys piden permisos para ser ejecutados, alta paja.

**Comment by PalumboN** [comment]
@asanzo dice si no es mejor apuntar a tener un installer

**Comment by fdodino** [comment]
Ok, hay algo investigado? Podemos agregar pantallas como para orientarnos un toque más?

**Comment by PalumboN** [comment]
Sí, los problemas son:

- Para deployar CLI hay que generar los ejecutables, por cada SO. Eso se está subiendo [en los assets del release](https://github.com/uqbar-project/wollok-ts-cli/releases/tag/v0.0.5).
- Cuando te descargas esos ejecutables, _no vienen con permisos para ejecutar_. Así que te los bajás, los abrís, y... WOLLOK NO FUNCIONA! :( Si les cambiás los permisos todo piola.
No recuerdo si el problema es de GitHub o de cómo se generan esos ejecutables...
- Hoy para generar todos los ejecutables (sobre todo Windows) solamente los puede hacer @ivojawer con su máquina. Estaría bueno, junto con esto, resolver el Continuos Deployment y que esos ejecutable se generen y se suban al crear el Release.

**Comment by ivojawer** [comment]
En realidad para windows entiendo que cualquier maquina con arquitectura x86 podria generarlos. De igual forma para las macs que corren con arm64.

Sobre los permisos algo que descubrí es que por algun motivo cuando zippeas los archivos del release no se pierden los permisos.

**Comment by fdodino** [comment]
ahí lo estuve viendo para que el CI lo suba automáticamente cuando releaseamos a master como con Wollok LSP IDE:

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/c3fa6996-c27d-4fc5-8657-22aa8daab8c8)

una vez que lo genero le cambio a mano los permisos a todos los ejecutables.
