### ISSUE TITLE
Hacer QA al CLI

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#8]
Necesitamos probar el cli contra **varios proyectos que se usen en el aula** para asegurarnos que corra más o menos bien.

Acá hay una posible lista de ellos para completar:
https://docs.google.com/spreadsheets/d/1Co9iVX3K69HxktaMaVHlHJicLAoZorYLdFiS9Moc-Ek/edit#gid=0

La idea es:
- Agregar ahí proyectos que sepamos que se usan en diversos cursos y unis (preferentemente con tests)
- Bajarse esos proyectos y correr `wollok test` con el cli sobre ellos y fijarse que pasen los tests
- Marcar brevemente en la planilla los proyectos revisados con OK si fue todo bien o no ok y algún comment si hubo algo mal
- Cargar todos los errores en issues en el proyecto correspondiente. (por ejemplo, si hay una validación que anda mal, cargarla en wollok-ts, o si es algo del cli cargarlo acá, cualquier cosa se puede mover sin drama)

**Comment by asanzo** [comment]
Mandar por 
- wollok-dev @ groups y 
- wollok-docentes @ groups y
- por discord

un mail pidiendo URLs de proyectos para probar

**Comment by fdodino** [comment]
Yo estoy corrigiendo los TPs y corregiré los parciales usando wollok-lsp + ts-cli

**Comment by PalumboN** [comment]
Grosssoooo Dodaiiinnnnnn!!!!

Porfa escribamos tests si encontramos algo raro :)

**Comment by fdodino** [comment]
Dalo por hecho!!

Por ahora lo más groso que encontré fue

- el error del REPL de los closures (no funcionan con parámetros, me parece bloqueante)
- el missing reference de proyectos que no saben encontrar su root folder (esto es para mí también bloqueante, le tiraría prioridad porque la UX es mala por una pavada)
- el error del REPL de determinar el candadito (no me parece tan terrible pero me parece que se relaciona con lo anterior, tiene prioridad para mí)
- el parser que incluye los espacios para calcular el final de un elemento (tampoco es tan terrible, pero afecta a cosas como el autocomplete y también para mostrar los errores en el validador, es una paja porque afecta a varios componentes)
- que coincidan los archivos wlk y wtest rompe los imports (esto también me parece high priority, no bloqueante, pero lo arreglaría con un workaround que comenté en el issue)

Todo lo otro son chiches.

**Comment by fdodino** [comment]
Dado que ya estuvimos corrigiendo @Juancete, y yo, y le estuvimos poniendo mucho cariño, doy por finalizado el ticket, cualquier novedad abrimos nuevos issues.
