### ISSUE TITLE
Con `powershell` se podría loguear un warning

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#80]
Con `powershell` se podría logear un warning

Tal vez este issue es más de CLI que de LSP.

_Originally posted by @PalumboN in https://github.com/uqbar-project/wollok-lsp-ide/pull/75#discussion_r1217098825_

**Comment by fdodino** [comment]
Cuál sería el warning que tenemos que agregar y en qué caso?

**Comment by PalumboN** [comment]
En Powershell no podemos armar el string de la regex para filtrar los tests (habría que mejorar esa api).
La mezcla de comillas que hay que generar no las soporta.

Así que cuando corres un test dentro de un archivo creo que corre todos los del archivo (o un comportamiento así inesperado).

 El warning sería:
No todos los features del CLI son soportados en Powershell, te recomendamos usar otra consola (cmd, bash, git).

**Comment by fdodino** [comment]
Imagino que ya habrán visto [cómo tratar de escapear los double quotes (vs. single quotes)](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3) en Powershell. Medio una paja, pero tengo mi notebook con una instalación de Windows, puedo probar, me gustaría ver si se puede hacer algo.

**Comment by fdodino** [comment]
ahora me queda la duda @PalumboN :

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/861da133-7b33-4a9e-8bc9-9ad9a77682fd)

Me instalé Powershell para Linux (no sabía que estaba esa opción) y ejecuté los tests y me anduvieron. Será el Powershell para Windows que tenga ese problema? Será otra cosa?

```bash
/usr/bin/wollok-ts-cli test 'testDeBiblioteca."tests de Cuidado con el Perro"."El precio con un precio base impar"' --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-paradigmos2 
```

me lo interpretó bien, y me dio el mismo resultado que correrlo con `Run test` desde el IDE, que corre con bash. Solo aparecen dos tests porque está subiéndose el bin (no tengo idea por qué).

**Comment by PalumboN** [comment]
Este issue lo encontramos con @ivojawer en Windows.
Probamos todas las posibilidades de escape de quotes pero no nos salió.

Ahora no recuerdo exactamente cuál era el problema, y si era solo con la CLI o desde el LSP que pasaba.

**Comment by ivojawer** [comment]
Cuando tenga a mano mi Windows lo pruebo porque en principio el problema era cuando había espacios en el string del test, que en tu prueba Fer funcionó perfecto.

**Comment by fdodino** [comment]
sí, yo lo tengo para ver también en Windows pero me da mucha flojera reiniciar jajaja

**Comment by fdodino** [comment]
Bueno, no me funciona en Windows - Powershell, principalmente porque Powershell apesta:

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/2d483315-aa67-487d-bc95-0f1fe58c7966)

Pero el powershell de Linux es gracioso que no tiene ese bug.

**Comment by fdodino** [comment]
Bueno, yo creo que tengo un workaround:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/6a0c7888-70c3-4402-9417-c47cb9c6c635)

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/5586a879-4ef9-4eb0-a2ed-ed37572980e6)

Y es ignorar las comillas del test para el fully qualified name:

```ts
  const targets = environment.descendants.filter(is(Test)).filter(test => {
    return (!filter || test.fullyQualifiedName.replaceAll('"', '').includes(filter)) &&
    !test.siblings().some(sibling => sibling.is(Test) && sibling.isOnly)
  }
```

tengo que probarlo en Linux/Mac para certificar que no considere las comillas, pero al menos funciona en Powershell.

**Comment by fdodino** [comment]
uh qué  mal!! meti un cambio directo a master. Sorry, pense que estaba en una rama aparte, no entendia nada.

**Comment by fdodino** [comment]
Jajajaja, encima meti un cambio con mi cuenta fakeDodain, todo mal, jajaja, tengo mal el teclado (no tengo las tildes) y encima estoy en GMT-0. Tengo absolutamente todo dado vuelta en mi Windows. Despues lo pruebo bien en Linux y si no meto cambiazo.

**Comment by fdodino** [comment]
bueno, ahí lo probé en Linux y anduvo ok. @ivojawer @PalumboN , uds. que son los mac-boys, avisen si funciona en Mac y doy por concluido el ticket.

**Comment by PalumboN** [comment]
Jajaja @fdodino cortaste toda la loozzzzz (?

Bueno, entiendo que lo que hiciste fue tocar el filter del comando de test. Yo tenía en mente mejorar la API (ene vez de estar jugando con las comillas y el manejo de strings). 
Onda en vez de solamente matchear los strings con el fqn tener una especie de parámetros opcionales:

```bash
wollok-cli test --file "saraza.wlk" --describe "nombre del describe" --test "nombre del test"
```

Pero blah, si ya lo tenés andando messiiiii. Creo que igual las comillas van a molestar, no sé, no pensé en la implementación jajaj

**Comment by fdodino** [comment]
Jajaja, sí... fue épico. Me gusta el cambio que proponés, si querés create un ticket para hacerlo más adelante aunque entiendo igual que Powershell hace percha todas las comillas, así que no se si vamos a zafar de ésa. La otra cosa que hice fue tratar de refactorizar un poco el comportamiento del código para separar si se corría un `only` test vs. un conjunto de tests.

**Comment by fdodino** [comment]
Cierro este issue para crear otro específico del cambio en la API
