### ISSUE TITLE
Cuando levantás el REPL sin un archivo explícito el diagrama dinámico muestra objetos que no están importados

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts-cli#89]
El REPL se comporta ok, cuando hacés `wollok-ts-cli repl`: no podés utilizar objetos y definiciones que están en algún wlk, y los podés importar, pero en el diagrama dinámico aparece la lista de objetos precargados. Eso puede resultar confuso. No se si es un problema del intérprete de wollok-ts que funciona lazy o bien del diagrama dinámico.

![replVsDiagramaDinamico](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/5499f590-4c3b-4626-9245-c24947aab385)

**Comment by fdodino** [comment]
mmm... acá me parece que está el tema:

```ts
export async function buildEnvironmentForProject(cwd: string): Promise<Environment> {
  const paths = await globby('**/*.@(wlk|wtest|wpgm)', { cwd })

  const debug = logger.getLevel() <= logger.levels.DEBUG

  if(debug) time('Reading project files')
  const files = await Promise.all(paths.map(async name =>
    ({ name, content: await readFile(join(cwd, name), 'utf8') })
  ))
  if(debug) timeEnd('Reading project files')

  if(debug) time('Building environment')
  try { return buildEnvironment(files) }
  finally { if(debug) timeEnd('Building environment' ) }
}
```

deberíamos usar para el REPL `autoImportPath`, que puede ser string o undefined. En el caso de ser undefined no estoy seguro de si queremos ejecutar el REPL sin un archivo definido o quieren importar todo el proyecto. En el caso del autoImportPath existente, es el archivo cuyas definiciones sí van a estar (las otras no dentro del contexto del REPL).

Yo agregaría un parámetro más que sea el filePath.

Viendo quiénes toquetearon el archivo hay bocha de gente, si alguno me tira un centro respecto a esta solución y a si hay otra mejor se agradece: @PalumboN @asanzo @FerRomMu @julimr @nscarcella

**Comment by fdodino** [comment]
Ah, ah, ah, el tema es que cuando buildean el environment si hay imports se rompe... ponele que example2.wlk haga import de example.wlk. Bueno, tengo que toquetearlo un poco más...

**Comment by fdodino** [comment]
Definitivamente no le encuentro la vuelta. Si hago `wollok-ts-cli repl example2.wlk` me aparecen los objetos de example.wlk también, pero no los puedo acceder desde ese contexto. Creo que hay algún tema cuando se definen los locals del REPL, deberían filtrarse aquellos que no están en la lista de objetos importados por más que lo tengas en el environment.

**Comment by fdodino** [comment]
Ahí vimos con el señor @PalumboN que es más para Wollok-ts, y que podría estar más copado que el buildEnvironment no tire un error si le pasás un file que tiene imports, y que los busque por el proyecto...

**Comment by PalumboN** [comment]
@fdodino para mí igual son 2 cosas distintas:

1. El diagrama no representa el punto de vista de la consola. Ahora te muestra todos los objetos del universo, incluso algunos que no están accesibles desde la consola. Y por lo que entiendo queremos que muestrar son solamente eso, para que no haya confusión.

2. Para mí el hecho que la VM tenga o no esos objetos en memoria para mí es anecdótico. Podemos hacer que efectivamente sea lazy pero eso es una "optimisación", no creo que valga la pena por este issue. Lo veo más relacionado a mejorar la API general de WollokTS que es algo que estaría piola cranear (podemos crear una épica).

En conclusión, pregunto: Ahora este issue no se puede arreglar eligiendo los objetos accesibles desde la consola? Es _fácil_ hacer eso? Si es así yo mandaría esa y abriría una épica en TS.

**Comment by fdodino** [comment]
@PalumboN 

1. Exacto, yo quiero ver en el diagrama lo mismo que puedo acceder desde la consola.
2. Coincido, es anecdótico y que sea lazy no forma parte del ticket ni de mi preocupación por ahora.

> En conclusión, pregunto: Ahora este issue no se puede arreglar eligiendo los objetos accesibles desde la consola? Es fácil hacer eso? 
Claro, mi idea era filtrarlo desde wollok-ts-cli y a la lona. Es _fácil_ hacer eso? No, así como está yo tengo una lista de referencias: las que son del REPL directas no tienen el `.`. El tema es que los que tienen `.` no los puedo filtrar entre los que son de definiciones que sí se importan vs. los que no se importan

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/bebdaf51-6f3c-496e-9ce0-8d7196f4d03d)

O sea, cómo distingo a `ivo` y `dodain` que están en example y no deberían aparecer, vs. `rasta` que está en example2 y que sí debería aparecer. Podría filtrar por el nombre del archivo, pero si example2 importa example lo debería tener en cuenta. Ok, podría hacer un import recursivo y obtener la lista de todos los archivos importados... pero acá siento que es responsabilidad de wollok-ts darme eso, la API tiene que poder decirme: "ésta es la lista de los archivos asociados a este file". Con eso yo ya soy feliz. Pero quiero validar con el resto que tenga sentido.

**Comment by fdodino** [comment]
@PalumboN , para que se entienda el ejemplo anterior este es el código:

```wollok
// example2.wlk
object rasta {
    const hoy = new Date()
    const a = [1] 
}

// example.wlk
object dodain {

}

object ivo {
  
}
```

example.wlk estaba en la carpeta raíz, después lo moví a `src`

**Comment by PalumboN** [comment]
@fdodino no tiene que ser recursivo, solamente necesitamos la lista de archivos (o packages) importados desde el REPL. Eso ya se tiene en un package REPL:
```ts
const importedFromConsole = interpreter.evaluation.environment.getNodeByFQN<Package>("REPL").imports
```

De esa forma, las raíces del diagrama son:
- Los WKO cuyas definiciones se encuentren en los imports de `importedFromConsole`
- Las locales definidas en la consola

Entiendo que el algoritmo, dada la lista de raíces, ya dibuja todo el grafo a partir de ellas.

**Comment by fdodino** [comment]
Bueno, a futuro me queda pasar este método a wollok-ts:

```ts
function getImportedDefinitionsFromConsole(interpreter: Interpreter): string[] {
  const imports = interpreter.evaluation.environment.getNodeByFQN<Package>(REPL).imports
  return imports.flatMap(imp => imp.children.map(child => (child as unknown as Reference<Entity>).name))
}
```

y pedir que me de los names y los ids. Cuando hice

```ts
import example.*
```

el target era undefined, pero puede ser porque había una carpeta `src` y los archivos eran hermanos. Por ahí no reconocía el directorio raíz del proyecto.
